{
 "title": "mydashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "target": "jvm.memory.used.area.heap.id.PS_Eden_Space"
    }
   ]
  },
  { "title": "System state", "type": "alertlist", "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 } },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_cpu{mode=\"user\"}",
     "legendFormat": "{{ cpu }}",
     "refCount": 1,
     "target": "alias(sumSeries(jvm.memory.max.area.heap.id.*), 'available')"
    },
    {
     "expr": "node_cpu{mode=\"user\"}",
     "legendFormat": "{{ cpu }}",
     "refCount": 1,
     "target": "alias(sumSeries(jvm.memory.used.area.heap.id.*), 'used')"
    }
   ]
  },
  {
   "title": "Cache Size (mem)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "target": "cache.size.estimate.bytes" }
   ]
  },
  {
   "title": "Cache size (items)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "cache.size.items" }
   ]
  },
  {
   "title": "Cache Hit / Miss rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "cache.stats.hit_rate" },
    { "target": "cache.stats.miss_rate" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "akka-http.akka.http.connections.active.count"
    }
   ]
  },
  {
   "title": "Redis access latency p99",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 10 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "target": "redis_client.timer.p99" }
   ]
  },
  {
   "title": "Redis access",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(redis_client.errors.m1_rate, 'errors count')"
    },
    {
     "target": "alias(nonNegativeDerivative(redis_client.success.count), 'successful requests rate')"
    }
   ]
  }
 ]
}